In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('data.xlsx')
df.head()

,ID,WBC,LYMp,MIDp,NEUTp,LYMn,MIDn,NEUTn,RBC,HGB,...,MCV,MCH,MCHC,RDWSD,RDWCV,PLT,MPV,PDW,PCT,PLCR
0,1,10.0,43.2,6.7,50.1,4.3,0.7,5.0,2.77,7.3,...,87.7,26.3,30.1,35.3,11.4,189.0,9.2,12.5,0.17,22.3
1,2,10.0,42.4,5.3,52.3,4.2,0.5,5.3,2.84,7.3,...,88.2,25.7,20.2,35.3,11.4,180.0,8.9,12.5,0.16,19.5
2,3,7.2,30.7,8.6,60.7,2.2,0.6,4.4,3.97,9.0,...,77.0,22.6,29.5,37.2,13.7,148.0,10.1,14.3,0.14,30.5
3,4,6.0,30.2,6.3,63.5,1.8,0.4,3.8,4.22,3.8,...,77.9,23.2,29.8,46.5,17.0,143.0,8.6,11.3,0.12,16.4
4,5,4.2,39.1,7.2,53.7,1.6,0.3,2.3,3.93,0.4,...,80.6,23.9,29.7,42.7,15.1,236.0,19.5,12.8,0.22,24.8

In [3]:
df=df[['MCV','MCH','MCHC','RDWCV','HGB']]
df.head()

    MCV   MCH  MCHC  RDWCV  HGB
0  87.7  26.3  30.1   11.4  7.3
1  88.2  25.7  20.2   11.4  7.3
2  77.0  22.6  29.5   13.7  9.0
3  77.9  23.2  29.8   17.0  3.8
4  80.6  23.9  29.7   15.1  0.4

In [4]:
df.isnull().sum()

MCV      0
MCH      0
MCHC     0
RDWCV    0
HGB      0
dtype: int64

In [5]:
(df<0).sum()

MCV      1
MCH      0
MCHC     0
RDWCV    0
HGB      1
dtype: int64

In [6]:
df=df[(df>=0).all(axis=1)]

In [7]:
(df<0).sum()

MCV      0
MCH      0
MCHC     0
RDWCV    0
HGB      0
dtype: int64

In [8]:
df

      MCV   MCH  MCHC  RDWCV   HGB
0    87.7  26.3  30.1   11.4   7.3
1    88.2  25.7  20.2   11.4   7.3
2    77.0  22.6  29.5   13.7   9.0
3    77.9  23.2  29.8   17.0   3.8
4    80.6  23.9  29.7   15.1   0.4
..    ...   ...   ...    ...   ...
495  86.4  27.4  31.7   12.2  13.2
496  76.7  24.0  31.4   13.8  11.6
497  68.8  22.7  33.0   10.6   9.9
498  70.6  21.9  30.9   11.0   7.4
499  72.0  24.4  33.5   12.3  10.3

[498 rows x 5 columns]